[project]
name = "fundmatch"
description = "Quadratic funding matcher"
authors = ["solidworkssa"]
telemetry = false
cache_dir = ".cache"

[contracts.fundmatch]
path = "contracts/fundmatch.clar"

[repl.analysis]
passes = ["check_checker"]
